[package]
name = "samefile"
version = "0.0.0-dev"
edition = "2024"
rust-version = "1.85.0"

[target."cfg(windows)".dependencies]
windows-sys = { version = ">=0.59.0, <1.0.0", features = [
  "Win32_Storage_FileSystem",
] }

[dev-dependencies]
tempfile = "3.24.0"
