[package]
name = "samefile"
version = "0.0.0-dev"
edition = "2024"

[target."cfg(windows)".dependencies]
windows-sys = { version = ">= 0.29, < 1", features = [
  "Win32_Foundation",
  "Win32_Storage_FileSystem",
] }

[dev-dependencies]
tempfile = "3.24.0"
