name: Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  compile-test-lint:
    name: Compile, Test & Lint
    strategy:
      matrix:
        runs-on: [macos-latest, ubuntu-latest, windows-latest]
        toolchain: [1.85.0, stable]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Install Rust
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --component clippy
          rustup default ${{ matrix.toolchain }}
      - name: Cache
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      - name: Compile
        run: cargo build --all-targets --locked --verbose
      - name: Test
        run: cargo test --all-targets --locked --verbose
      - name: Lint
        run: cargo clippy --all-targets --locked --verbose
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Format
        run: cargo fmt --check --all --verbose
